version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: 
          name: build
          command: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout  
      - run: npm i
      - run: 
          name: test
          command: npm run test      

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:               
      - checkout      
      - run: 
          name: analyze
          command: npm audit     

workflows:
  first-workflow:
    jobs:
      - build
      - test:
         requires :
          - build
      - analyze:
          requires :
           - test      
